# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtnPrincipal.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QHBoxLayout,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_vtnPrincipal(object):
    def setupUi(self, vtnPrincipal):
        if not vtnPrincipal.objectName():
            vtnPrincipal.setObjectName(u"vtnPrincipal")
        vtnPrincipal.resize(753, 622)
        font = QFont()
        font.setPointSize(8)
        vtnPrincipal.setFont(font)
        self.centralwidget = QWidget(vtnPrincipal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.btnGuardar = QPushButton(self.centralwidget)
        self.btnGuardar.setObjectName(u"btnGuardar")
        self.btnGuardar.setGeometry(QRect(210, 510, 101, 41))
        self.btnGuardar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnlimpiar = QPushButton(self.centralwidget)
        self.btnlimpiar.setObjectName(u"btnlimpiar")
        self.btnlimpiar.setGeometry(QRect(390, 510, 101, 41))
        self.btnlimpiar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.txtNombre = QLineEdit(self.centralwidget)
        self.txtNombre.setObjectName(u"txtNombre")
        self.txtNombre.setGeometry(QRect(270, 150, 301, 31))
        self.txtNombre.setMaxLength(100)
        self.cbtiposervicio = QComboBox(self.centralwidget)
        self.cbtiposervicio.addItem("")
        self.cbtiposervicio.addItem("")
        self.cbtiposervicio.addItem("")
        self.cbtiposervicio.addItem("")
        self.cbtiposervicio.addItem("")
        self.cbtiposervicio.addItem("")
        self.cbtiposervicio.addItem("")
        self.cbtiposervicio.addItem("")
        self.cbtiposervicio.addItem("")
        self.cbtiposervicio.setObjectName(u"cbtiposervicio")
        self.cbtiposervicio.setGeometry(QRect(270, 350, 131, 31))
        self.cbtiposervicio.setEditable(False)
        self.cbtiposervicio.setDuplicatesEnabled(False)
        self.cbtiposervicio.setFrame(True)
        self.txtApellido = QLineEdit(self.centralwidget)
        self.txtApellido.setObjectName(u"txtApellido")
        self.txtApellido.setGeometry(QRect(270, 200, 301, 31))
        self.txtApellido.setMaxLength(100)
        self.txtcedula = QLineEdit(self.centralwidget)
        self.txtcedula.setObjectName(u"txtcedula")
        self.txtcedula.setGeometry(QRect(270, 100, 151, 31))
        self.txtcedula.setMaxLength(10)
        self.txtcostservicio = QLineEdit(self.centralwidget)
        self.txtcostservicio.setObjectName(u"txtcostservicio")
        self.txtcostservicio.setGeometry(QRect(270, 300, 111, 31))
        self.txtcostservicio.setInputMethodHints(Qt.ImhNone)
        self.txtcostservicio.setMaxLength(10)
        self.lbNombre = QLabel(self.centralwidget)
        self.lbNombre.setObjectName(u"lbNombre")
        self.lbNombre.setGeometry(QRect(180, 140, 91, 51))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        self.lbNombre.setFont(font1)
        self.lbApellido = QLabel(self.centralwidget)
        self.lbApellido.setObjectName(u"lbApellido")
        self.lbApellido.setGeometry(QRect(180, 190, 91, 51))
        self.lbApellido.setFont(font1)
        self.lbCedula = QLabel(self.centralwidget)
        self.lbCedula.setObjectName(u"lbCedula")
        self.lbCedula.setGeometry(QRect(190, 90, 81, 51))
        self.lbCedula.setFont(font1)
        self.lbRuta = QLabel(self.centralwidget)
        self.lbRuta.setObjectName(u"lbRuta")
        self.lbRuta.setGeometry(QRect(210, 240, 61, 51))
        self.lbRuta.setFont(font1)
        self.lbCostServicio = QLabel(self.centralwidget)
        self.lbCostServicio.setObjectName(u"lbCostServicio")
        self.lbCostServicio.setGeometry(QRect(80, 290, 191, 51))
        self.lbCostServicio.setFont(font1)
        self.lbTipoServicio = QLabel(self.centralwidget)
        self.lbTipoServicio.setObjectName(u"lbTipoServicio")
        self.lbTipoServicio.setGeometry(QRect(130, 340, 131, 51))
        self.lbTipoServicio.setFont(font1)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(250, 20, 338, 61))
        self.horizontalLayout = QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.btninsertar = QPushButton(self.groupBox)
        self.btninsertar.setObjectName(u"btninsertar")

        self.horizontalLayout.addWidget(self.btninsertar)

        self.btnbuscar = QPushButton(self.groupBox)
        self.btnbuscar.setObjectName(u"btnbuscar")

        self.horizontalLayout.addWidget(self.btnbuscar)

        self.btnactualizar = QPushButton(self.groupBox)
        self.btnactualizar.setObjectName(u"btnactualizar")

        self.horizontalLayout.addWidget(self.btnactualizar)

        self.btneliminar = QPushButton(self.groupBox)
        self.btneliminar.setObjectName(u"btneliminar")

        self.horizontalLayout.addWidget(self.btneliminar)

        self.cbruta = QComboBox(self.centralwidget)
        self.cbruta.addItem("")
        self.cbruta.addItem("")
        self.cbruta.addItem("")
        self.cbruta.addItem("")
        self.cbruta.addItem("")
        self.cbruta.addItem("")
        self.cbruta.addItem("")
        self.cbruta.setObjectName(u"cbruta")
        self.cbruta.setGeometry(QRect(270, 250, 131, 31))
        vtnPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(vtnPrincipal)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 753, 21))
        vtnPrincipal.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(vtnPrincipal)
        self.statusbar.setObjectName(u"statusbar")
        vtnPrincipal.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.txtcedula, self.txtNombre)
        QWidget.setTabOrder(self.txtNombre, self.txtApellido)
        QWidget.setTabOrder(self.txtApellido, self.cbruta)
        QWidget.setTabOrder(self.cbruta, self.txtcostservicio)
        QWidget.setTabOrder(self.txtcostservicio, self.cbtiposervicio)
        QWidget.setTabOrder(self.cbtiposervicio, self.btnGuardar)
        QWidget.setTabOrder(self.btnGuardar, self.btnlimpiar)
        QWidget.setTabOrder(self.btnlimpiar, self.btninsertar)
        QWidget.setTabOrder(self.btninsertar, self.btnbuscar)
        QWidget.setTabOrder(self.btnbuscar, self.btnactualizar)
        QWidget.setTabOrder(self.btnactualizar, self.btneliminar)

        self.retranslateUi(vtnPrincipal)

        QMetaObject.connectSlotsByName(vtnPrincipal)
    # setupUi

    def retranslateUi(self, vtnPrincipal):
        vtnPrincipal.setWindowTitle(QCoreApplication.translate("vtnPrincipal", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        vtnPrincipal.setToolTip(QCoreApplication.translate("vtnPrincipal", u"Ingrese solo n\u00fameros", None))
#endif // QT_CONFIG(tooltip)
        self.btnGuardar.setText(QCoreApplication.translate("vtnPrincipal", u"GUARDAR", None))
        self.btnlimpiar.setText(QCoreApplication.translate("vtnPrincipal", u"LIMPIAR", None))
        self.txtNombre.setPlaceholderText(QCoreApplication.translate("vtnPrincipal", u"Ingrese el nombre del usuario", None))
        self.cbtiposervicio.setItemText(0, QCoreApplication.translate("vtnPrincipal", u"Seleccionar", None))
        self.cbtiposervicio.setItemText(1, QCoreApplication.translate("vtnPrincipal", u"Transporte Rapido", None))
        self.cbtiposervicio.setItemText(2, QCoreApplication.translate("vtnPrincipal", u"Logistico Personas", None))
        self.cbtiposervicio.setItemText(3, QCoreApplication.translate("vtnPrincipal", u"Logistico Mercancias", None))
        self.cbtiposervicio.setItemText(4, QCoreApplication.translate("vtnPrincipal", u"Mensajeria", None))
        self.cbtiposervicio.setItemText(5, QCoreApplication.translate("vtnPrincipal", u"Paqueteria Urbana", None))
        self.cbtiposervicio.setItemText(6, QCoreApplication.translate("vtnPrincipal", u"Transporte Corporativo De Personal", None))
        self.cbtiposervicio.setItemText(7, QCoreApplication.translate("vtnPrincipal", u"Traslados Tur\u00edsticos", None))
        self.cbtiposervicio.setItemText(8, QCoreApplication.translate("vtnPrincipal", u"Distribuci\u00f3n De Carga", None))

        self.cbtiposervicio.setCurrentText(QCoreApplication.translate("vtnPrincipal", u"Seleccionar", None))
        self.txtApellido.setPlaceholderText(QCoreApplication.translate("vtnPrincipal", u"Ingrese el apellido del usuario", None))
#if QT_CONFIG(tooltip)
        self.txtcedula.setToolTip(QCoreApplication.translate("vtnPrincipal", u"Ingrese solo n\u00fameros", None))
#endif // QT_CONFIG(tooltip)
        self.txtcedula.setInputMask("")
        self.txtcedula.setPlaceholderText(QCoreApplication.translate("vtnPrincipal", u"Cedula del usuario", None))
        self.txtcostservicio.setInputMask("")
        self.txtcostservicio.setText("")
        self.txtcostservicio.setPlaceholderText(QCoreApplication.translate("vtnPrincipal", u"0.00$", None))
        self.lbNombre.setText(QCoreApplication.translate("vtnPrincipal", u"Nombre:", None))
        self.lbApellido.setText(QCoreApplication.translate("vtnPrincipal", u"Apellido:", None))
        self.lbCedula.setText(QCoreApplication.translate("vtnPrincipal", u"Cedula:", None))
        self.lbRuta.setText(QCoreApplication.translate("vtnPrincipal", u"Ruta:", None))
        self.lbCostServicio.setText(QCoreApplication.translate("vtnPrincipal", u"Costo del servicio:", None))
        self.lbTipoServicio.setText(QCoreApplication.translate("vtnPrincipal", u"Tipo Servicio:", None))
        self.groupBox.setTitle("")
        self.btninsertar.setText(QCoreApplication.translate("vtnPrincipal", u"Insertar", None))
        self.btnbuscar.setText(QCoreApplication.translate("vtnPrincipal", u"Buscar", None))
        self.btnactualizar.setText(QCoreApplication.translate("vtnPrincipal", u"Actualizar", None))
        self.btneliminar.setText(QCoreApplication.translate("vtnPrincipal", u"Eliminar", None))
        self.cbruta.setItemText(0, QCoreApplication.translate("vtnPrincipal", u"Seleccionar", None))
        self.cbruta.setItemText(1, QCoreApplication.translate("vtnPrincipal", u"Norte", None))
        self.cbruta.setItemText(2, QCoreApplication.translate("vtnPrincipal", u"NorOeste", None))
        self.cbruta.setItemText(3, QCoreApplication.translate("vtnPrincipal", u"Sur", None))
        self.cbruta.setItemText(4, QCoreApplication.translate("vtnPrincipal", u"SurEste", None))
        self.cbruta.setItemText(5, QCoreApplication.translate("vtnPrincipal", u"Este", None))
        self.cbruta.setItemText(6, QCoreApplication.translate("vtnPrincipal", u"Oeste", None))

    # retranslateUi

